"""add onboarding_sessions table

Revision ID: dc7f251c8c33
Revises: 1edaed9a34f6
Create Date: 2026-01-06 18:07:03.420632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc7f251c8c33'
down_revision: Union[str, None] = '1edaed9a34f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_sessions',
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('collected_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conversation_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_sessions_phone_number'), 'onboarding_sessions', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_sessions_phone_number'), table_name='onboarding_sessions')
    op.drop_table('onboarding_sessions')
    # ### end Alembic commands ###
