"""add whatsapp connection fields to onboarding

Revision ID: 9e06fdca4153
Revises: dc7f251c8c33
Create Date: 2026-01-07 18:28:41.676557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e06fdca4153'
down_revision: Union[str, None] = 'dc7f251c8c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_sessions', sa.Column('connection_token', sa.String(length=100), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('whatsapp_phone_number_id', sa.String(length=100), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('whatsapp_waba_id', sa.String(length=100), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('whatsapp_access_token', sa.Text(), nullable=True))
    op.create_index(op.f('ix_onboarding_sessions_connection_token'), 'onboarding_sessions', ['connection_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_sessions_connection_token'), table_name='onboarding_sessions')
    op.drop_column('onboarding_sessions', 'whatsapp_access_token')
    op.drop_column('onboarding_sessions', 'whatsapp_waba_id')
    op.drop_column('onboarding_sessions', 'whatsapp_phone_number_id')
    op.drop_column('onboarding_sessions', 'connection_token')
    # ### end Alembic commands ###
